vich_uploader:
    db_driver: orm
    mappings:
        ygocards:
            uri_prefix: /uploads/images/ygocards
            upload_destination: '%kernel.project_dir%/public/uploads/images/ygocards'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
